version: '3.7'

services:
  car_booking:
    image: car_booking
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    # networks:
    #   - carbooking
    #     external: true
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/car_booking

  user_service:
    image: user_service
    build:
      context: user_service/build
      dockerfile: Dockerfile
    networks:
      - carbooking
    #     external: true

  notification:
    image: notification
    build:
      context: notification_service
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/car_booking
    #network_mode: "host"
networks:
  carbooking:
    external: true
    
    
    