version: '3.7'

services:
  car_booking:
    image: car_booking
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/car_booking

  user_service:
    image: user_service
    build:
      context: user_service/build
      dockerfile: Dockerfile
    depends_on:
      - notification

  notification:
    image: notification
    build:
      context: notification_service
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/car_booking
    #network_mode: "host"

  car_module:
    image: car_module
    build:
      context: car_module/build
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/car_booking

    
    
    