version: '3'

  car_booking:
    image: car_booking
    build:
      context: build
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/car_booking
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true