version: '3.7'

services:
  car_booking:
    image: car_booking
    build:
      context: build
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/car_booking
    network_mode: "host"
    ports:
      - "8080:8080"
    